### ISSUE TITLE
Map styles reset when other state changes

### ISSUE THREAD

**Issue by ebrelsford** [stamen/map-compare#42]
It looks like the handler for other state changes (eg view mode) is using the original maps.

Reproduce:
 1. Change either map pane to a different style
 2. Change the view mode

The map pane you changed the style for will be reset to the original style.

**Comment by aparlato** [comment]
@ebrelsford I'm unable to replicate this bug. Is it possible that this behavior is the result of an invalid local config? If so, maybe config validation is the solution. If not, do you mind providing me a config file that lets this happen and a url link to replicate?
