### ISSUE TITLE
Consider adding a way to view feature data within a map pane

### ISSUE THREAD

**Issue by ebrelsford** [stamen/map-compare#43]
Likely only for Mapbox GL styles. On click, show which features you clicked on and the data associated with those features.

Some things to consider:
 * Is this always on, or an option that you need to enable?
 * What should the interface look like?
 * Should the feature remain selected in the URL state?

**Comment by aparlato** [comment]
My initial take here is to do the simplest implementation we can and see if that suits us.

> Is this always on, or an option that you need to enable?

I think always being on should be fine so long as the popup doesn't come up every time you move the map.

> What should the interface look like?

Something close to the popup that exists when inspecting in Mapbox Studio or Maputnik seems appropriate to me to start.

> Should the feature remain selected in the URL state?

I'm inclined to say no. I question the utility of this and I think it would open up more surface area for bugs or confusing behavior (eg mismatches between viewport and selected features, persisted url features and changing data, etc).

@ebrelsford let me know if this simple implementation sounds good to you to start!
